### ISSUE TITLE
Can you add a tilemapping system in your pixelpencil app please

### ISSUE THREAD

**Issue by DiweshThakur** [therealbluepandabear/therealbluepandabear#1]
•I have been working on a game, I have all the sprite and tilesets but couldn't find any application for tilemapping and level design on Android.

•It would be grateful if add this feature in your app.
•I contacted you here as I could not post any issues on the issue page of pixapencil.

**Comment by therealbluepandabear** [comment]
Hi, 

Unfortunately, development is over so I cannot add this new feature.

Sorry to disappoint.

Regards,
thebluepandabear
